// Code generated by mtribes. DO NOT EDIT.

package com.mtribes.mtspace.section

import com.massive.mtclient.sdk.Broker
import com.massive.mtclient.sdk.CreateChild
import com.massive.mtclient.sdk.Section
import com.massive.mtclient.sdk.Template
import com.mtribes.mtspace.experience.HeroExperience
import com.mtribes.mtspace.experience.BannerExperience
import kotlin.reflect.KClass

class HomepageBodySection(
    id: String,
    parentId: String,
    broker: Broker,
    childTypes: Map<String, Any> = mapOf(
        "VGd1POB" to HeroExperience::class,
        "NW0bo31" to BannerExperience::class
    ),
    template: Template = Template("5ozXdgW", "16539")
) : Section(id, parentId, broker, childTypes, template) {

    enum class Supported(val type: KClass<*>) {
        HERO(HeroExperience::class),
        BANNER(BannerExperience::class)
    }

    override fun createChild(): CreateChild = { templateId, id, parentId, broker ->
        when (templateId) {
            "VGd1POB" -> HeroExperience(
                id,
                parentId,
                broker
            )
            "NW0bo31" -> BannerExperience(
                id,
                parentId,
                broker
            )
            else -> null
        }
    }
}
