// Code generated by mtribes. DO NOT EDIT.

package com.mtribes.mtspace

import com.massive.mtclient.sdk.api.model.Fallbacks

val fallbacks = Fallbacks(
    v = 42365,
    json = """{"3q6rn6p":{"on":true,"sid":"ojBovxy","v":36469,"data":"{\"1\":\"https://pkw.us.astcdn.com/img/sample/1=x700.jpg\"}","pid":"yxE8Q2R"},"8x6DeEy":{"on":true,"sid":"9RDRWkq","v":19836,"data":"{\"1\":{\"opacity\":1.000,\"value\":\"#6f58c4\"},\"2\":{\"opacity\":1.000,\"value\":\"#2363ae\"}}"},"Rn25dEk":{"on":true,"sid":"XajVWeM","v":13192,"data":"{\"1\":\"Banner\"}","pid":"yxE8Q2R"},"nLK0ZEJ":{"on":true,"sid":"2Po3pBb","v":35347,"data":"{\"1\":\"Banner\"}","pid":"yxE8Q2R"},"yxE8Q2R":{"on":true,"sid":"4pLMZlk","v":14243,"se":[{"id":"3q6rn6p","et":"VGd1POB"},{"id":"nLK0ZEJ","et":"NW0bo31"},{"id":"Rn25dEk","et":"NW0bo31"}]}}"""
)
