// Code generated by mtribes. DO NOT EDIT.

package com.mtribes.mtspace

import android.content.Context
import android.util.Log
import com.massive.mtclient.sdk.api.model.Fallbacks
import java.io.IOException

const val FALLBACKS_ASSET_NAME = "fallbacks.json"
const val FALLBACKS_VERSION = 39269

internal fun createFallbacks(context: Context): Fallbacks {
    return try {
        val input = context.assets.open(FALLBACKS_ASSET_NAME)

        val size = input.available()

        val buffer = ByteArray(size)

        input.read(buffer)
        input.close()

        Fallbacks(v = FALLBACKS_VERSION, json = String(buffer))
    } catch (e: IOException) {
        Log.e("Fallbacks", "fallbacks conversion failed !", e)
        Fallbacks(v = FALLBACKS_VERSION, "")
    }
}
