// Code generated by mtribes. DO NOT EDIT.

package com.mtribes.mtspace.collection

import com.massive.mtclient.sdk.Broker
import com.massive.mtclient.sdk.Collection
import com.massive.mtclient.sdk.Template
import com.mtribes.mtspace.section.HomepageBodySection
import com.mtribes.mtspace.experience.HeaderExperience

class HomepageCollection(
    id: String,
    childIds: List<String>,
    broker: Broker,
    template: Template = Template("5Lb7ZGo", "16538")
) : Collection(id, broker, template) {

    @JvmField
    val header = HeaderExperience(childIds[0], id, broker)
    @JvmField
    val body = HomepageBodySection(childIds[1], id, broker)
}
