// Code generated by mtribes. DO NOT EDIT.

package com.mtribes.mtspace.experience

import android.os.Parcelable
import com.google.gson.annotations.SerializedName
import com.massive.mtclient.sdk.Broker
import com.massive.mtclient.sdk.Experience
import com.massive.mtclient.sdk.Template
import kotlinx.parcelize.Parcelize

class BannerExperience(
    id: String,
    parentId: String,
    broker: Broker,
    template: Template = Template("NW0bo31", "16543")
) :
    Experience<BannerExperienceData>(id, parentId, broker, template) {

    override val defaultDataType: Class<BannerExperienceData> = BannerExperienceData::class.java
}

@Parcelize
data class BannerExperienceData(
    @SerializedName("1") @JvmField val label: String? = null
) : Parcelable
