// Code generated by mtribes. DO NOT EDIT.

package com.mtribes.mtspace.experience

import android.os.Parcelable
import com.google.gson.annotations.SerializedName
import com.massive.mtclient.sdk.Broker
import com.massive.mtclient.sdk.ColorProperty
import com.massive.mtclient.sdk.Experience
import com.massive.mtclient.sdk.Template
import kotlinx.parcelize.Parcelize

class HeaderExperience(
    id: String,
    parentId: String,
    broker: Broker,
    template: Template = Template("yDBpL8a", "23067")
) :
    Experience<HeaderExperienceData>(id, parentId, broker, template) {

    override val defaultDataType: Class<HeaderExperienceData> = HeaderExperienceData::class.java
}

@Parcelize
data class HeaderExperienceData(
    @SerializedName("1") @JvmField val backgroundColor: ColorProperty? = null,
    @SerializedName("2") @JvmField val gradientColor: ColorProperty? = null
) : Parcelable
