// Code generated by mtribes. DO NOT EDIT.

package com.mtribes.mtspace.experience

import android.os.Parcelable
import com.google.gson.annotations.SerializedName
import com.massive.mtclient.sdk.Broker
import com.massive.mtclient.sdk.Experience
import com.massive.mtclient.sdk.Template
import kotlinx.parcelize.Parcelize

class HeroExperience(
    id: String,
    parentId: String,
    broker: Broker,
    template: Template = Template("VGd1POB", "16542")
) :
    Experience<HeroExperienceData>(id, parentId, broker, template) {

    override val defaultDataType: Class<HeroExperienceData> = HeroExperienceData::class.java
}

@Parcelize
data class HeroExperienceData(
    @SerializedName("1") @JvmField val source: String? = null
) : Parcelable
